/**
 * DNA mutation detection client — calls Evo 2 via our Lambda endpoint.
 * Full potato GBSS reference sequence (X83220.1, 5428 bp) embedded for display.
 */

const EVO2_API = 'https://f33ilwj535.execute-api.us-east-1.amazonaws.com';

// Full potato GBSS gene — granule-bound starch synthase (X83220.1)
const REFSEQ =
  'GATCTGACAAGTCAAGAAAATTGCCATTGAAGTCAGAGAATGAGAAGTTCGAGACACTGGCTACGGCTCATCCAAGTAGC' +
  'ATTTGTATGGAATGTGACTTGTTTTATCTTTGCTCAGGAACCTGGACCTATAAGTGTTCCTATTTAACTAGCTAGTTCTA' +
  'TTGCCAAGTTTGTTTGGCGTCGTGCTGCTTATACAAACTTTGATCACATATATACGTACGTTCACCATTTATTAATTAGG' +
  'GAACTTTCACATGTAGCCACTCAAAAATAGCTCAATTATTCTCCATAGCTATAGTTTGATAATTACAATCTGTAGCTATA' +
  'TGTTATAGGGAGGAGAGAGGGGGCAAAGAGTGGGAGAAAGGTGAATTGTATATGTATATAGGTTAGATAATTGTATATTA' +
  'TACATATGTATTTGTATATTCTGGCGAATTATACATATACAAACGTGACTAATTATACACACTCGAAGTCAACCTGCATA' +
  'ATTAATGTATAATGTTAGTCGTGAGTGATAATTATAGCAAACTATAGGTATGATGAGTAATTAAGTAGTATAAGTTTGCT' +
  'TAATCGCGTAATTTTCCCCATTAATTATATATAAAATTCTTAAGAAATTCTCGAGGCAGTAAAGGTTCCACAAATTGAAA' +
  'TCAGGAAGAAACTATTAACTAATCTATTTTCTTTTCTTCAACGACTACTACTTATTATATTGGCTCTAAAGATAAGAGGA' +
  'TAATGAAACAAAGGAAGAAGCTTTAACGAGATAGAAAATTATATTACTCCGTTTTGTTCATTACTTAACAAATGCAACAG' +
  'TATCTTGTACCAAATCCTTTCTCTCTTTTCAAACTTTTCTATTTGGCTGTTGACAGAGTAATCAGGATACAAACCACAAG' +
  'TATTTAATTGACTCATCCACCAGATATTATGATTTATGAATCCTCGAAAAGCCTATCCATTAAGTTCTCATCTATGGATA' +
  'TACTTGACAGTTTCTTCCTATTTGGGTATTTTTTTTTCCTGCCAAGTGGAACGGAGACATGTTATGTTGTATACGGGAAG' +
  'CTCGTTAAAAAAAAAAATACAATAGGAAGAAATGTAACAAACATTGAATGTTGTTTTTAACCATCCTTCCTTTTAGCAGT' +
  'GTATCAATTTTGTAATAGAACCATGCATCTCAATCTTAATACTAAAAAATGCAACAAAATTCTAGTGGAGGGACCAGTAC' +
  'CAGTACATTAGATATTATTTTTTATTACTATAATAATATTTTAATTAACACGAGACATAGGAATGTCAAGTGGTAGCGGT' +
  'AGGAGGGAGTTGGTTTAGTTTTTTAGATACTAGGAGACAGAACCGGAGGGGCCCATTGCAAGGCCCAAGTTGAAGTCCAG' +
  'CCGTGAATCAACAAAGAGAGGGCCCATAATACTGTCGATGAGCATTTCCCTATAATACAGTGTCCACAGTTGCCTTCCGC' +
  'TAAGGGATAGCCACCCGCTATTCTCTTGACACGTGTCACTGAAACCTGCTACAAATAAGGCAGGCACCTCCTCATTCTCA' +
  'CACTCACTCACTCACACAGCTCAACAAGTGGTAACTTTTACTCATCTCCTCCAATTATTTCTGATTTCATGCATGTTTCC' +
  'CTACATTCTATTATGAATCGTGTTATGGTGTATAAACGTTGTTTCATATCTCATCTCATCTATTCTGATTTTGATTCTCT' +
  'TGCCTACTGAATTTGACCCTACTGTAATCGGTGATAAATGTGAATGCTTCCTCTTCTTCTTCTTCTTCTCAGAAATCAAT' +
  'TTCTGTTTTGTTTTTGTTCATCTGTAGCTTGGTAGATTCCCCTTTTTGTAGACCACACATCACATGGCAAGCATCACAGC' +
  'TTCACACCACTTTGTGTCAAGAAGCCAAACTTCACTAGACACCAAATCAACCTTGTCACAGATAGGACTCAGGAACCATA' +
  'CTCTGACTCACAATGGTTTAAGGGCTGTTAACAAGCTTGATGGGCTCCAATCAAGAACTAATACTAAGGTAACACCCAAG' +
  'ATGGCATCCAGAACTGAGACCAAGAGACCTGGATGCTCAGCTACCATTGTTTGTGGAAAGGGAATGAACTTGATCTTTGT' +
  'GGGTACTGAGGTTGGTCCTTGGAGCAAAACTGGTGGACTAGGTGATGTTCTTGGTGGACTACCACCAGCCCTTGCAGTAA' +
  'GTCTTTCATTTGGTTACCTACTCATTCATTACTTATTTTGTTTAGTTAGGTTCTACTGCATCAGTCTTTTTATCATTTAG' +
  'GCCCGCGGACATCGGGTAATGACAATATCCCCCCGTTATGACCAATACAAAGATACTTGGGATACTAGCGTTGCGGTTGA' +
  'GGTACATCTTTCTATATTGATACGGTACAATATTGTTCTCTTACATTTCCTGATTCAAGAATGTGATCCGCTACTTTATC' +
  'TGCAGGTCAAAGTTGGAGACAGCATTGAAATTGTTCGTTTCTTTCACTGCTATAAACGTGGGGTTGATCGTGTTTTTGTT' +
  'GACCACCCAATGTTCTTGGAGAAAGTAAGTAAGTATATTATGATTATGAATCCATCCTGAGGGATACGCAGAACAGGTCA' +
  'TTTTGAATATCTTTTAACTCTACTGGTGCTTTTACTCTTTTAAGGTTTGGGGTAAAACTGGTTCAAAAATCTATGGCCCC' +
  'AAAGCTGGACTAGATTATCTGGACAATGAACTTAGGTTCAGCTTGTTGTGTCAAGTAAGTTAGTTACTTGTTATACTGTT' +
  'GTCTTGATTTTTATGTGGCATTTTACTCTTTAATCGTTTTTTTAACCTTGTTTTCTCAGGCAGCCCTAGAGGCACCTAAA' +
  'GTTTTGAATTTGAACAGTAGCAACTACTTCTCAGGACCATATGGTAATTAACACATCCTAGTTTCAGAAAACTCCTTAGT' +
  'ATATCATTGTAGGTAATCATCTTTATTTTGCCTATTCCTGCAGGAGAGGATGTTCTCTTCATTGCCAATGATTGGCACAC' +
  'AGCTCTCATTCCTTGCTACTTGAAGTCAATGTACCAGTCCAGAGGAATCTATTTGAATGCCAAGGTAAAATTTCTTTGTA' +
  'TTCACTTGATTGCACTTTACCCTGCAAATCAGTAAGGTTGTATTAATATATGATAAATTTCACATTGCCTCCAGGTCGCT' +
  'TTCTGCATCCATAACATTGCCTACCAAGGCCGATTTTCTTTCTCTGACTTCCCTCTTCTCAATCTTCCTGATGAATTCAG' +
  'GGGTTCTTTTGATTTCATTGATGGGTATGTATTTAATGCTTGAAATCAGACCACCAACTTTTGAAGCTCTTTTGATGCTA' +
  'GTAAATTGAGTTTTTAAAATTTTGCAGTTATGAGAAGCCTGTTAAGGGTAGGAAAATCAACTGGATGAAGGCTGGGATAT' +
  'TAGAATCACATAGGGTGGTTACAGTGAGCCCATACTATGCCCAAGAACTTGTCTCTGCTGTTGACAAGGGTGTTGAATTG' +
  'GACAGTGTCCTTCGAAAGACTTGCATAACTGGGATTGTGAATGGCATGGATACACAAGAGTGGAACCCAGCGACTGACAA' +
  'ATACACAGATGTCAAATACGATATAACCACTGTAACATAAGATTTTTCCAACTCCAGTATATACTAAATTATTTTGTATG' +
  'TTTATGAAATTAAAGAGTTCTTGCTAATCAAAATCTCTATACAGGTCATGGACGCAAAACCTTTACTAAAGGAGGCTCTT' +
  'CAAGCAGCAGTTGGCTTGCCTGTTGACAAGAAGGTCCCTTTGATTGGCTTCATCGGCAGACTTGAGGAGCAGAAAGGTTC' +
  'AGATATTCTTGTTGCTGCAATTCACAAGTTCATCGGATTGGATGTTCAAATTGTAGTCCTTGTAAGTACCAAATGGACTC' +
  'ATGGTATCTCTCTTGTTGAGTTTACTTGTGCCGAAACTGAAATTGACCTGCTACTCATCCTATGCATCAGGGAACTGGCA' +
  'AAAAGGAGTTTGAGCAGGAGATTGAACAGCTCGAAGTGTTGTACCCTAACAAAGCTAAAGGAGTGGCAAAATTCAATGTC' +
  'CCTTTGGCTCACATGATCACTGCTGGTGCTGATTTTATGTTGGTTCCAAGTAGATTTGAACCTTGTGGTCTCATTCAGTT' +
  'ACATGCTATGCGATATGGAACAGTAAGAACCATAAGAGCTTGTACCTTTTTACTGATTTTTAAAAAAAGAATCATAAGAC' +
  'CTTGTTTTCCGTCTAAAGTTTAATAGCCAACTAAATGTTACTGCAGCAAGCTTTTCATTTCTGAAAATTGGTTATCTGAT' +
  'TTTAACATAATCACATGTGAGTCAGGTGCCAATCTGTGCATCGACTGGTGGACTTGTTGACACTGTGAAAGAAGGCTATA' +
  'CTGGATTCCATATGGGAGCCTTCAATGTTGAAGTATGTGATTTTACATCAATTGTGTACTTGTACATAGTCCATTCTCGT' +
  'CTTGATATACCCCTTGTTGCATAAACATTAACTTATTGCTTCTTGAATTTGGTTAGTGCGATGTTGTTGACCCAGCTGAT' +
  'GTGCTTAAGATAGTAACAACAGTTGCTAGAGCTCTTGCAGTCTATGGCACCCTTGCGTTTGCTGAGATGATAAAAAATTG' +
  'CATGTCAGAGGAGCTCTCCTGGAAGGTAGGTGTCAATTTGATAATTTGCGTAGGTACTTCAGTTTGTTGTTCTCGTCAGC' +
  'ACTGATGGATGCCAACTGGTGTTCATGCAGGAACCTGCCAAGAAATGGGAGACATTGCTATTGGGCTTAGGAGCTTCTGG' +
  'CAGTGAACCCGGTGTTGAAGGGGAAGAAATCGCTCCACTTGCCAAGGAAAATGTAGCCACTCCCTAAATGAGCTTTGGTT' +
  'ATCCTTGTTTCAACAATAAGATCATTAAGCAAACGTATTTACTAGCGAACTATGTAGAACCCTATTATGGGGTCTCAATC' +
  'ATCTACAAAATGATTGGTTTTTGCTGGGGAGCAGCAGCATATTAGGCTGTAAAATCCTGGTTAATGTTTTTGTAGGTAAG' +
  'GGCTATTTAAGGTGGTGTGGATCAAAGTCAATAGAAAATAGTTATTACTAGCGTTTGCAACTAAATACTTAGTAATGTAG' +
  'CATAAATAATACTAGTAGCTAATATATATGCGTGAATTTGTTGTACCTTTTCTTGCATAATTATTTGCAGTACATATATA' +
  'ATGAAAATTACCCAAGGAATCAATGTTTCTTGCTCCGTCCTCCTTTGATGATTTTTTACTCAATACAGAGCTAGTGTGTT' +
  'AAGTTATAAATTTTGTTTAAAAGAAGTAATCAATTTCAAATTAGTTGGTTGGTCATATGAAAGAAGCTGGCAGGCTAACT' +
  'TTGAGGAGATGGCTATTGAATTTCAAAGTGATTATGTGAAAACAATGCAACATCTATGTCAATCAACACTTAAATTATTG' +
  'CATTTAGAAAGATATTTTTGATCCCATGACACATTCATTCATAAAGTAAGGTAGTATGTATGATTGAA';

export async function scoreMutation(kind, pos, alt, window = 512) {
  const body = { kind, pos, window };
  if (alt) body.alt = alt;
  const res = await fetch(`${EVO2_API}/score`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`Evo2 API error: ${res.status}`);
  return res.json();
}

export async function scorePendingMutations(state) {
  const pending = (state.genetics?.mutations || []).filter(m => !m.scored);
  if (pending.length === 0) return state;

  const s = JSON.parse(JSON.stringify(state));

  for (const mut of pending) {
    const stMut = s.genetics.mutations.find(m => m.id === mut.id);
    if (!stMut) continue;
    try {
      const result = await scoreMutation(mut.kind, mut.pos, mut.alt);
      stMut.scored = true;
      stMut.delta_score = result.delta_score;
      stMut.interpretation = result.interpretation;
      stMut.probabilities = result.probabilities;
      stMut.ref_log_prob = result.ref_log_prob;
      stMut.alt_log_prob = result.alt_log_prob;
      stMut.ref = result.mutation?.ref || REFSEQ[mut.pos - 1] || '?';
    } catch (err) {
      console.warn('[dna] Score failed for', mut.id, err.message);
      stMut.scored = true;
      stMut.interpretation = 'error';
      stMut.delta_score = 0;
    }
  }

  return s;
}

/**
 * Get a window of the real reference sequence around a mutation position.
 * Returns { before, ref, after, pos } for display.
 */
export function getSequenceWindow(pos, windowSize = 40) {
  const half = Math.floor(windowSize / 2);
  const start = Math.max(0, pos - 1 - half);
  const before = REFSEQ.slice(start, pos - 1);
  const ref = REFSEQ[pos - 1] || '?';
  const after = REFSEQ.slice(pos, pos + half);
  return { before, ref, after, pos, start: start + 1 };
}

/** Get the reference base at a 1-indexed position. */
export function getRefBase(pos) {
  return REFSEQ[pos - 1] || '?';
}
